export const AllTalks = [
  {
    title: 'Demistifying urql using urql-devtools',
    description: '',
    presentedAt: [
      {
        eventDate: '5-26-20',
        eventName: 'GraphQL Denver',
        eventType: 'meetup',
        eventUrl: '',
        recordedPresentationUrl: '',
        location: 'virtual',
      },
      {
        eventDate: '7-16-20',
        eventName: 'RESTLess London',
        eventType: 'meetup',
        eventUrl: '',
        recordedPresentationUrl: '',
        location: 'virtual',
      },
    ],
    exportedSlidesUrl: '',
    hostedSlidesUrl: '',
    previewImg: '',
  },
  {
    title: 'Evolution of an API: A Case for GraphQL',
    description: '',
    presentedAt: [
      {
        eventDate: '9-20-19',
        eventName: 'UtahJS',
        eventType: 'conference',
        eventUrl: 'https://conf.utahjs.com/',
        recordedPresentationUrl: '',
        location: 'Salt Lake City, UT',
      },
    ],
    exportedSlidesUrl: '',
    hostedSlidesUrl: '',
    previewImg: '',
  },
  {
    title: 'TypeScript + React: A Love Story',
    description: '',
    presentedAt: [
      {
        eventDate: '4-16-19',
        eventName: 'React Denver',
        eventType: 'meetup',
        eventUrl: 'https://www.meetup.com/ReactDenver/events/kgrmmqyzgbvb/',
        recordedPresentationUrl: 'https://youtu.be/iBlGIS-UQsw?t=1638',
        location: 'Denver, CO',
      },
    ],
    exportedSlidesUrl: '',
    hostedSlidesUrl: '',
    previewImg: '',
  },
  {
    title: 'React to React Native: How Hard Could It Be?',
    description: '',
    presentedAt: [
      {
        eventDate: '11-15-19',
        eventName: 'RVA.js',
        eventType: 'conference',
        eventUrl: '',
        recordedPresentationUrl: '',
        location: 'Richmond, VA',
      },
      {
        eventDate: '5-28-19',
        eventName: 'DenverScript',
        eventType: 'meetup',
        eventUrl: '',
        recordedPresentationUrl: '',
        location: 'Denver, CO',
      },
    ],
    exportedSlidesUrl: '',
    hostedSlidesUrl: '',
    previewImg: '',
  },
  {
    title: 'ML on the CL',
    description: 'Maching learning on the command line.',
    presentedAt: [
      {
        eventDate: '6-28-18',
        eventName: 'js.la',
        eventType: 'meetup',
        eventUrl: 'https://js.la',
        recordedPresentationUrl: 'https://youtu.be/MzrDy4s8MF8',
        location: 'Los Angeles, CA',
      },
    ],
    exportedSlidesUrl: '',
    hostedSlidesUrl: '',
    previewImg: '',
  },
  {
    title: 'How TypeScript Made Me a Better JavaScript Developer',
    description: '',
    presentedAt: [
      {
        eventDate: '10-25-18',
        eventName: 'Formidable Denver Open House',
        eventType: 'meetup',
        eventUrl: 'https://formidable-denver.eventbrite.com',
        recordedPresentationUrl: null,
        location: 'Denver, CO',
      },
    ],
    exportedSlidesUrl: '',
    hostedSlidesUrl: '',
    previewImg: '',
  },
  {
    title: 'Teaching Machines How to Do Cool Things with JavaScript',
    description: '',
    presentedAt: [
      {
        eventDate: '4-28-18',
        eventName: 'Zeit Day',
        eventType: 'conference',
        eventUrl: 'https://zeit.co/day',
        recordedPresentationUrl: 'https://youtu.be/QaV7a64mUYE',
        location: 'San Francisco, CA',
      },
    ],
    exportedSlidesUrl: '',
    hostedSlidesUrl: '',
    previewImg: '',
  },
]
